version: '3.8'
services:
  apache:
    image: httpd:latest
    container_name: mqp-dashboard-frontend
    ports:
    - '8080:80'
    volumes:
    - ./build:/Users/di93sig/software/projects/LRZ/QIS/jenkins/www/portal.lrz.de/